const actionTypes = {
  ADD_USER_TO_SEARCH_LIST: "ADD_USER_TO_SEARCH_LIST",
  REMOVE_USER_FROM_SEARCH_LIST: "REMOVE_USER_FROM_SEARCH_LIST",
  SET_TOKEN: "SET_TOKEN",
  UNSET_TOKEN: "UNSET_TOKEN",
};
export default actionTypes;
